/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ladyjustice.glb --types --transform --shadows 
Files: public/ladyjustice.glb [10.94MB] > C:\Users\Shrey\Desktop\Prayatna 3.0\NyayAI\frontend\ladyjustice-transformed.glb [519.83KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    edit1: THREE.Mesh
  }
  materials: {
    ['tripo_mat_50fb2bec-b861-4101-a34f-eceebf27a040.003']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ladyjustice-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.edit1.geometry} material={materials['tripo_mat_50fb2bec-b861-4101-a34f-eceebf27a040.003']} />
    </group>
  )
}

useGLTF.preload('/ladyjustice-transformed.glb')
